import React from 'react';

const Day = () => {
    return (
        <>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time">
                    <div className="task">
                        <span>English lesson</span>
                        <div className='time-of-task'>8-30 - 9-30</div>
                    </div>
                </div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
            <li className='item-content'>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
                <div className="item-time"></div>
            </li>
        </>
    )
}
export default Day